id: I7D70A83D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T20:18:25+00:00'
last_modified: '2022-06-08T02:11:00.530270+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6137
  title: ཕྱི་རྒྱལ་གྱི་གྲགས་ཅན་དམག་དཔོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    2D82:
      image_group_id: I1KG8455
      title: ''
      total_pages: 504
      order: 1
      base_file: 2D82.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
