id: P004594
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG6137
  title: ཕྱི་རྒྱལ་གྱི་གྲགས་ཅན་དམག་དཔོན།
  author: ''
  volumes:
    a751e7a18ecc40bf9592beb97232f23a:
      image_group_id: I1KG8455
      title: ''
      volume_number: 1
      total_pages: 504
      base_file: v001.txt
